# https://github.com/yarnpkg/berry/issues/6247
# Due to a bug with yarn v4 and node>20.12, yarn v3 is used
# also when yarn v4 is used, the below script runs in the withNightlyPipeline wrapper, but is not ESM compatible
# https://github.com/hmcts/cnp-jenkins-library/blob/master/resources/uk/gov/hmcts/pipeline/yarn/format-v4-audit.js
# hence, yarn v3 is used until this is resolved
yarnPath: .yarn/releases/yarn-3.8.7.cjs
